.

diff --git a/module1_task1/Makefile b/module1_task1/Makefile
--- a/module1_task1/Makefile
+++ b/module1_task1/Makefile
@@ -1,15 +1,30 @@
+# Define variables
+POST_TITLE ?= Untitled
+POST_NAME ?= untitled
+HUGO = hugo
+DIST_DIR = dist
+
+# Define targets
+
+## Build the website from markdown and configuration files
 build:
-	@hugo
+    @$(HUGO) --source . --destination $(DIST_DIR) --theme ananke
 
+## Cleanup the contents of the dist directory
 clean:
-	@rm -rf dist
+    @rm -rf $(DIST_DIR)/*
 
+## Create a new blog post with a given name and title
 post:
-	@POST_NAME=$$(openssl rand -hex 1); \
-	POST_NAME+= $$(openssl rand -hex 1); \
-	POST_TITLE=$$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1); \
-	hugo new posts/$$POST_NAME.md; \
-	echo "---\n\
-	title: '$$POST_TITLE'\n\
-	date: $$(date +"%Y-%m-%dT%H:%M:%S%z")\n\
-	---" > content/posts/$$POST_NAME.md
+    @if [ -z "$(POST_TITLE)" ] || [ -z "$(POST_NAME)" ]; then \
+        echo "Please set POST_TITLE and POST_NAME environment variables"; \
+        exit 1; \
+    fi
+    @hugo new --kind post $(DIST_DIR)/$(POST_NAME).md
+    @sed -i '' 's/title = ""/title = "$(POST_TITLE)"/' $(DIST_DIR)/$(POST_NAME).md
+
+## Show the available targets and their usage
+help:
+    @echo "Available targets:"
+    @grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
+
